/**
 * Converts HTML generated by react-native-pell-rich-editor to match
 * the TipTap JSON/HTML format expected by the Web App and backend.
 */
export function pellToTipTap(html) {
  if (!html) return '';

  let clean = html.trim();

  // Replace <div> tags with <p>
  clean = clean
    .replace(/<div(?=[\s/>])([^>]*)>/gi, '<p$1>')
    .replace(/<\/div>/gi, '</p>');

  // Normalize inline tags
  clean = clean
    // Match complete tag names: <br> is not <b>, and <img> is not <i>.
    .replace(/<b(?=[\s/>])([^>]*)>/gi, '<strong$1>')
    .replace(/<\/b>/gi, '</strong>')
    .replace(/<i(?=[\s/>])([^>]*)>/gi, '<em$1>')
    .replace(/<\/i>/gi, '</em>')
    .replace(/<strike(?=[\s/>])([^>]*)>/gi, '<s$1>')
    .replace(/<\/strike>/gi, '</s>')
    .replace(/<del(?=[\s/>])([^>]*)>/gi, '<s$1>')
    .replace(/<\/del>/gi, '</s>');

  // Note: Aggressive paragraph-joining regex removed to preserve intentional newlines.

  return clean;
}
