/**
 * Converts HTML generated by react-native-pell-rich-editor to match
 * the TipTap JSON/HTML format expected by the Web App and backend.
 */
export function pellToTipTap(html) {
  if (!html) return '';
  return html
    // Block elements
    .replace(/<div([^>]*)>/gi, '<p$1>')
    .replace(/<\/div>/gi, '</p>')
    // Inline elements
    .replace(/<b([^>]*)>/gi, '<strong$1>')
    .replace(/<\/b>/gi, '</strong>')
    .replace(/<i([^>]*)>/gi, '<em$1>')
    .replace(/<\/i>/gi, '</em>')
    .replace(/<strike([^>]*)>/gi, '<s$1>')
    .replace(/<\/strike>/gi, '</s>')
    .replace(/<del([^>]*)>/gi, '<s$1>')
    .replace(/<\/del>/gi, '</s>');
}
