/**
 * Converts HTML generated by react-native-pell-rich-editor to match
 * the TipTap JSON/HTML format expected by the Web App and backend.
 */
export function pellToTipTap(html) {
  if (!html) return '';

  let clean = html.trim();

  // Replace <div> tags with <p>
  clean = clean
    .replace(/<div([^>]*)>/gi, '<p$1>')
    .replace(/<\/div>/gi, '</p>');

  // Normalize inline tags
  clean = clean
    .replace(/<b([^>]*)>/gi, '<strong$1>')
    .replace(/<\/b>/gi, '</strong>')
    .replace(/<i([^>]*)>/gi, '<em$1>')
    .replace(/<\/i>/gi, '</em>')
    .replace(/<strike([^>]*)>/gi, '<s$1>')
    .replace(/<\/strike>/gi, '</s>')
    .replace(/<del([^>]*)>/gi, '<s$1>')
    .replace(/<\/del>/gi, '</s>');

  // Join fragmented <p> tags created by editor formatting that don't contain manual linebreaks (<br>)
  clean = clean.replace(/<\/p>\s*<p>(?!\s*<br\s*\/?>)/gi, ' ');

  // Clean up any double spaces generated by joining
  clean = clean.replace(/  +/g, ' ');

  return clean;
}
